version: 0.1.0.{build}
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '0.1.0'
  package_version: '0.1.0'
  assembly_version: '0.1.0'
  file_version: '0.1.0'
  informational_version: '0.1.0'
before_build:
- cmd: nuget restore
build:
  project: Vortex.AutoMapper.Extensions.sln
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: j8GC+Px8nrnFxVSj/1CIR+qV69zYanb8CVZauRM5F47xxUfRPHcsYVleLSVmctvG
  on:
    branch: release